### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by andreasala98** [gnn4dr/DRKG#34]
Hi, when I try to run `dglke_train`  on my Windows 10 I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\u1123073\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\u1123073\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\u1123073\Anaconda3\Scripts\dglke_train.exe\__main__.py", line 7, in <module>
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dglke\train.py", line 144, in main
    train_sampler_head = train_data.create_sampler(args.batch_size,
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dglke\dataloader\sampler.py", line 379, in create_sampler
    return EdgeSampler(self.g,
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dgl\contrib\sampling\sampler.py", line 662, in __init__
    self._seed_edges = utils.toindex(self._seed_edges)
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dgl\utils\internal.py", line 271, in toindex
    return data if isinstance(data, Index) else Index(data, dtype)
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dgl\utils\internal.py", line 26, in __init__
    self._initialize_data(data)
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dgl\utils\internal.py", line 33, in _initialize_data
    self._dispatch(data)
  File "C:\Users\u1123073\Anaconda3\lib\site-packages\dgl\utils\internal.py", line 58, in _dispatch
    raise InconsistentDtypeException('Index data specified as %s, but got: %s' %
dgl.utils.internal.InconsistentDtypeException: DGL now requires the input tensor to have the same dtype as the
 graph index's dtype(which you can get by g.idype). Index data specified as int64, but got: int32
```

Is maintenance still active for this repo? Could you please have a look at this?

**Comment by andreasala98** [comment]
I fixed the version but got the same error
` File "C:\Users\u1123073\Anaconda3\envs\dglEnv\lib\site-packages\dgl\utils.py", line 47, in _dispatch
    raise DGLError('Index data must be an int64 vector, but got: %s' % str(data))
dgl._ffi.base.DGLError: Index data must be an int64 vector, but got: tensor([270771, 431361, 189684,  ...,  91473,  78302, 365505],
       dtype=torch.int32)`
